### ISSUE TITLE
Dashing-js plugin is not getting installed in node version 4.2.2

### ISSUE THREAD

**Issue by kaushik030** [fabiocaseri/dashing-js#33]
make: Leaving directory `/usr/lib/node_modules/dashing-js/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error:`make`failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/dashing-js/node_modules/node-sass
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm WARN install:node-sass@0.7.0 node-sass@0.7.0 install:`node build.js`
npm WARN install:node-sass@0.7.0 Exit status 1
/usr/lib
└── (empty)

npm ERR! code 1

**Comment by chriswhong** [comment]
I am having the same issue with node 0.12.2, npm install -g dashing-js 

```
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "dashing-js"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.7.0 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chriswhong/Sites/dashing-js/npm-debug.log
```

**Comment by matt7277** [comment]
Looks like I am experiencing the same problem here. Seems like this is a verified bug, would love to see if someone has a viable solution. I have copy/pasted my error output below. 

FYI - I tried this on a variety of Linux AWS servers and received the same error across installations. The output below comes from a fresh AWS AMI built by Bitnami for Node.JS/MongoDB. The results from my Ubuntu 14.04 HVM attempts were the same:

sudo npm install -g dashing-js
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"5.1.1","npm":"3.3.12"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"5.1.1","npm":"3.3.12"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"5.1.1","npm":"3.3.12"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"5.1.1","npm":"3.3.12"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"5.1.1","npm":"3.3.12"})
npm WARN excluding symbolic link test/fixtures/app/views/.#application.js.coffee.erb -> sam@pursuit.41266
/opt/bitnami/nodejs/bin/dashing-js -> /opt/bitnami/nodejs/lib/node_modules/dashing-js/bin/dashing-js

> node-sass@0.7.0 install /opt/bitnami/nodejs/lib/node_modules/dashing-js/node_modules/node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/opt/bitnami/nodejs/lib/node_modules/dashing-js/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:7:0:
../sass_context_wrapper.h:10:3: error: ‘uv_work_t’ does not name a type
   uv_work_t request;
   ^
../sass_context_wrapper.h:20:3: error: ‘uv_work_t’ does not name a type
   uv_work_t request;
   ^
../binding.cpp:13:20: error: variable or field ‘WorkOnContext’ declared void
 void WorkOnContext(uv_work_t* req) {
                    ^
../binding.cpp:13:20: error: ‘uv_work_t’ was not declared in this scope
../binding.cpp:13:31: error: ‘req’ was not declared in this scope
 void WorkOnContext(uv_work_t* req) {
                               ^
../binding.cpp:19:22: error: variable or field ‘MakeOldCallback’ declared void
 void MakeOldCallback(uv_work_t* req) {
                      ^
../binding.cpp:19:22: error: ‘uv_work_t’ was not declared in this scope
../binding.cpp:19:33: error: ‘req’ was not declared in this scope
 void MakeOldCallback(uv_work_t* req) {
                                 ^
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory`/opt/bitnami/nodejs/lib/node_modules/dashing-js/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-71-generic
gyp ERR! command "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/bitnami/nodejs/lib/node_modules/dashing-js/node_modules/node-sass
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm WARN install:node-sass@0.7.0 node-sass@0.7.0 install: `node build.js`
npm WARN install:node-sass@0.7.0 Exit status 1
/opt/bitnami/nodejs/lib
└── (empty)

npm ERR! code 1

**Comment by spadusa** [comment]
There's at least one pending pull request with a viable fix: https://github.com/fabiocaseri/dashing-js/pull/32/files

**Comment by admin-django** [comment]
Is this plugin no longer active? Dashing-js not installing on new nodejs version?
