### ISSUE TITLE
dashing-js trying to install old node-sass@0.7.0

### ISSUE THREAD

**Issue by karthikeayan** [fabiocaseri/dashing-js#41]
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sunka04\AppData\Roaming\npm\node_modules\dashing-js\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunka04\AppData\Roaming\npm-cache\_logs\2018-02-17T19_18_14_829Z-debug.log
```

PS C:\Users\sunka04\Documents\Source> npm --version
5.6.0
PS C:\Users\sunka04\Documents\Source> node --version
v8.9.4

**Comment by vijayjangid** [comment]
Facing the same issue, is anyone looking into this?

**Comment by MichalTestowy** [comment]
Same thing happens for me. Any advice would be appreciated

**Comment by orbmis** [comment]
Same issue here - seems like a blocker to actually this library at the moment.

**EDIT:**

This is how I got it working:

```
npm install git+https://github.com/simbro/dashing-js.git

./node_modules/dashing-js/bin/dashing-js new my-sweet-dashboard
```

**Comment by guicattani** [comment]
Thanks a lot, simbro! You saved me big time! 

Edit:
simbro deleted his fork

**Comment by tusharkhanka** [comment]
> Thanks a lot, simbro! You saved me big time!
> 
> Edit:
> simbro deleted his fork

Do you have a fork? I am facing this issue
